version: '3'

services:
  db:
    container_name: local_db
    image: postgres:13.7-alpine
    environment:
      POSTGRES_DB: poc
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
#    volumes:
#      - ./local_db/init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./local_db/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      sam-local:
        ipv4_address: 172.18.0.10
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      # - ./local_db/pgadmin:/var/lib/pgadmin
      - ./local_db/servers.json:/pgadmin4/servers.json
    ports:
      - "8080:80"
    networks:
      - sam-local
    restart: unless-stopped

networks:
  sam-local:
    name: sam_local
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
