version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "poc"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-xrwykzupczmh"
s3_prefix = "poc"
region = "eu-central-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.local_invoke.parameters]
parameter_overrides=[
    "DatabaseUser=user",
    "DatabasePassword=password",
    "DatabaseHost=172.18.0.10",
    "DatabaseName=poc"
]
