AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  poc

  SAM Template for poc

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 300
    Runtime: python3.9
    Handler: function.app.lambda_handler
    Architectures:
      - x86_64
    Layers:
      - !Ref CommonDependenciesLayer

Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: swe-bucket-bugsbunny

  SQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: swe-sqs
      
  CommonDependenciesLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      ContentUri: dependencies
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9

  ScrapingServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/scraping/
      Environment:
        Variables:
          INSTA_USERNAME: ''
          INSTA_PASSWORD: ''
          INSTA_SESSIONS_TABLE: 'poc-instagram-sessions'
          BUCKET_NAME: !Ref Bucket  # IMPORTANT: if running locally, set this variable manually!
      Policies:
        - AWSLambdaDynamoDBExecutionRole

  ScoringServiceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: services/scoring/
      Policies:
        - ComprehendBasicAccessPolicy: {}
        - SQSPollerPolicy:
            QueueName: swe-aws
        - S3CrudPolicy: 
            BucketName: swe-bucket-bugsbunny
      Events:
        SQSEvent:
          Type: SQS
          Properties:
            Queue: !Ref SQSQueue
            BatchSize: 5
      

Outputs:
  ScrapingServiceFunction:
    Description: 'ScrapingService Lambda Function ARN'
    Value: !GetAtt ScrapingServiceFunction.Arn

  ScoringServiceFunction:
    Description: 'ScoringService Lambda Function ARN'
    Value: !GetAtt ScoringServiceFunction.Arn

