openapi: 3.0.0
info:
  title: PoC API
  version: 0.1.0
  
paths:
  /posts/{postId}:
    get:
      summary: Returns a Post by ID
      parameters:
        - name: postId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Post in JSON format
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '404':
          description: Post not found
                  
  /posts:
    get:
      summary: Returns all Post
      responses:
        '200':
          description: JSON array of Post
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Post'
    post:
      summary: Scrape and analyze a new Post
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - type: object
                  properties:
                    url:
                      type: string
                      example: https://www.instagram.com/p/CeBpBUMsd0K
                - type: object
                  properties:
                    username:
                      type: string
                      example: ic3peak
      responses:
        '200':
          description: TODO
          
  /locations/{locationId}:
    get:
      summary: Returns a Location by ID
      parameters:
        - name: locationId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: Location in JSON format
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Location'
        '404':
          description: Location not found
                
  /locations:
    get:
      summary: Returns all Location
      responses:
        '200':
          description: JSON array of Location
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/Location'
                  
  /profiles/{profileId}:
    get:
      summary: Returns a SocialProfile by ID
      parameters:
        - name: profileId
          in: path
          required: true
          schema:
            type: integer
            minimum: 1
      responses:
        '200':
          description: SocialProfile in JSON format
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/SocialProfile'
        '404':
          description: SocialProfile not found
                
  /profiles:
    get:
      summary: Returns all SocialProfile
      responses:
        '200':
          description: JSON array of SocialProfile
          content: 
            application/json:
              schema:
                type: array
                items: 
                  $ref: '#/components/schemas/SocialProfile'
                  
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: integer
          example: 4
        caption:
          type: string
          example: A very nice day at place X
        profile:
          $ref: '#/components/schemas/SocialProfile'
        location:
          allOf:
            - nullable: true
            - $ref: '#/components/schemas/Location'
        score:
          allOf:
            - nullable: true
            - $ref: '#/components/schemas/PostScore'
    SocialProfile:
      type: object
      properties:
        id:
          type: integer
          example: 4
        username:
          type: string
          example: ic3peak
    Location:
      type: object
      properties:
        id:
          type: integer
          example: 4
        name:
          type: string
          example: X
        lat:
          type: number
          example: 55.7535579
        long:
          type: number
          example: 37.6187217
        score:
          type: number
          example: 4.6
    PostScore:
      type: object
      properties:
        media_score:
          type: number
          example: 4.5
        caption_score:
          type: number
          example: 4.5
  